### ISSUE TITLE
ToDo - Tuesday

### ISSUE THREAD

**Issue by Juhyun22** [Juhyun22/Juhyun22#5]
2022년 1월 25일 (화)
- [x] git 올리기
- [x] JSP 문제 풀이
- [x] MyBatis 알아보기 .. 구문!
- [x] Servlet, MyBatis, Spring 등 어떤 역할인지!
